### ISSUE TITLE
pathwayEnrichment using list of genes instead of DESeq2::results()? 

### ISSUE THREAD

**Issue by yimwy** [bioconductor-source/pathlinkR#1]
Hi, congratulations on the extremely useful package for RNAseq analysis visualization. As shown in title, I am curious in whether the pathwayEnrichment function can be performed using a list of informative genes (from WGCNA module for instance) instead of DESeq2::results()? 

Thank you in advance!

**Comment by lshep** [comment]
This repository is not a current active location for maintainer questions.  Please ask on the [Bioconductor support site](https://support.bioconductor.org/)  or on the [PathlinkR landing page](https://bioconductor.org/packages/devel/bioc/html/pathlinkR.html) there are links to the [pathlinkR github](https://github.com/hancockinformatics/pathlinkR)
