### ISSUE TITLE
Questions about species information

### ISSUE THREAD

**Issue by 146107576** [bioconductor-source/pathlinkR#2]
Hello, I would like to know if this R package can only analyze the genes of humans? Can genes from other species, such as mice, rats, and rabbits, be used with this pack?

**Comment by lshep** [comment]
This is not the right location to currently ask questions about bioconductor packages.  Please ask at support.bioconductor.org or look for the bug report link on the Bioconductor package landing page https://www.bioconductor.org/packages/release/bioc/html/pathlinkR.html
